language: ruby
rvm:
  - 2.0.0
  - 1.9.3
env:
  - GEM=will_paginate
  - GEM=kaminari
gemfile:
  - gemfiles/Gemfile.rails-3-2
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-head
matrix:
  allowed_failures:
  - gemfile: gemfiles/Gemfile.rails-head
